### ISSUE TITLE
Documentation conflict.

### ISSUE THREAD

**Issue by freman** [BlaT2512/spanet-api#2]
**Offending file/documentation**

spanet.md

**Describe the bug**

Two items share same Line and Bit in documentation.

> 6.4.5 Lights Colour
> Line: R6
> Read Bit: 4
> Data Type: Integer
> Range: 0 to 30
> Data: Integer represents colour from 0 to 30

> 6.5.6 Time Out Mode
> Line: R6
> Read Bit: 4
> Data Type: Integer
> Range: 10 to 30
> Data: Integer is time in minutes before pump and blower auto time-out

**Expected behavior**
They should be different

**Comment by freman** [comment]
I think Time Out is R6, 21

**Comment by freman** [comment]
While I'm here

Auto Sanitise is R7, 2

**Comment by BlaT2512** [comment]
Thankyou, I will check up those 2 now and shortly update the documentation
