### ISSUE TITLE
API Operating  Environment

### ISSUE THREAD

**Issue by ellyse18** [BlaT2512/spanet-api#5]
I assume there are no operating environment operations like power and current available via the API? At least I didn't see anything now that I have had a look.

Would be so handy to have this info and control.

**Comment by BlaT2512** [comment]
Unfortunately no this information is not available directly through the API. I suspect this information would be available, however, through the technician support interface/API (used with the support mode PIN in the app), although have no idea what the endpoints are for this.

**Comment by Northgated** [comment]
Ok thanks, just thought I would check even though I thought that was the case
